MODEL:
  META_ARCHITECTURE: "PanopticFCN"
  WEIGHTS:  "{ros_path}/panopticFCN/scripts/model/model_0831_trasfer.pth"
  MASK_ON: True
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [1.0, 1.0, 1.0]
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  
  POSITION_HEAD:
    THING:
      NUM_CLASSES: 4 #HM 9
      THRES: 0.01
      TOP_NUM: 200
    STUFF:
      THRES: 0.1
      NUM_CLASSES: 17 #HM 23
      WITH_THING: False  # Check that this is not a problem
      ALL_CLASSES: True
  SEM_SEG_HEAD: 
    NUM_CLASSES: 17 #HM 23
  KERNEL_HEAD:  
    INSTANCE_SCALES: ((1, 128), (64, 256), (128, 512), (256, 1024), (512, 2048),)
  TENSOR_DIM: 150  # Adapted because max inst. per img > 100
  INFERENCE:
    INST_THRES: 0.5
    SIMILAR_THRES: 0.97
    COMBINE:
      STUFF_AREA_LIMIT: 2048

DATASETS:
  # TRAIN: ("coco_2017_train_panoptic_separated",)
  # TEST: ("coco_2017_val_panoptic_separated",)
  NAME: "Cityscapes"  
  TRAIN: ("cityscapes_fine_panoptic_train_separated",)
  TEST: ("cityscapes_fine_panoptic_val_separated",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 1e-4
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  POLY_LR_POWER: 0.9
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
  WARMUP_METHOD: "linear"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 35.0
  IMS_PER_BATCH: 16
  MAX_ITER: 10000 #HM
  CHECKPOINT_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (352, 384, 416, 448, 480, 512)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 400
  MAX_SIZE_TRAIN: 854
  MAX_SIZE_TEST: 666
  MASK_FORMAT: "bitmask"
VERSION: 2

